"""The take's tmux session: private server, generated config, consoles with shell hooks,
and the on-screen layout (spec 9)."""

from __future__ import annotations

import asyncio
import re
import shlex
from collections.abc import Callable
from importlib.resources import files

from ..errors import EnvironmentProblem, StepFailed
from ..loader.model import ConsoleSpec, Scenario
from ..transport import Transport
from .driver import Console
from .remote import remote_shell_command
from .tmux import Tmux

SESSION = "scenarioplay"
ACCENT = "colour214"  # the active console's border and title

TMUX_CONF = """\
# Generated by ScenarioPlay for one take.
set -g history-limit 100000
set -g escape-time 0
set -g status off
set -g mouse off
set -g set-titles off
set -g bell-action none
set -g visual-bell off
set -g default-terminal "screen-256color"
setw -g remain-on-exit on
setw -g allow-rename off
setw -g automatic-rename off
"""

# Split layouts: every pane shows its console's title on its top border; the active
# console's border and title are highlighted (spec 9.2).
_ACTIVE_TITLE = f"#[fg=colour16#,bg={ACCENT}#,bold] #{{@sp_title}} #[default]"
_BORDER_FORMAT = f"#{{?pane_active,{_ACTIVE_TITLE}, #{{@sp_title}} }}"
PANES_CONF = f"""\
setw -g pane-border-status top
setw -g pane-border-format "{_BORDER_FORMAT}"
setw -g pane-border-style "fg=colour240"
setw -g pane-active-border-style "fg={ACCENT}"
"""

# Tabs: one window per console, a tab bar on top.
TABS_CONF = f"""\
set -g status on
set -g status-position top
set -g status-left ""
set -g status-right ""
set -g status-style "bg=colour236,fg=colour250"
setw -g window-status-format " #W "
setw -g window-status-current-format "#[fg=colour16,bg={ACCENT},bold] #W "
"""

# tmux preset for each split layout.
SPLIT_PRESETS = {"split-horizontal": "even-horizontal", "split-vertical": "even-vertical",
                 "grid": "tiled"}


def _hook_template(name: str) -> str:
    return (files("scenarioplay.console") / "hooks" / name).read_text(encoding="utf-8")


def _cells(size: str | int | None, total: int) -> int | None:
    """`30%` or `40` -> a number of cells within `total`."""
    if size is None:
        return None
    text = str(size)
    m = re.fullmatch(r"(\d+)(%?)", text)
    if not m:
        return None
    value = int(m.group(1))
    cells = total * value // 100 if m.group(2) else value
    return max(2, min(cells, total - 2))


def _render(template: str, **values: str) -> str:
    for key, value in values.items():
        template = template.replace(f"@@{key}@@", value)
    return template


class Session:
    def __init__(self, transport: Transport, runtime_dir: str, take_id: str,
                 log: Callable[[str, str], None]):
        self.transport = transport
        self.runtime_dir = runtime_dir
        self.tmux = Tmux(transport, f"scenarioplay-{take_id}")
        self.consoles: dict[str, Console] = {}  # open consoles, in screen order
        self.closed: dict[str, Console] = {}
        self.specs: dict[str, ConsoleSpec] = {}
        self.layout = "single"
        self.default_prompt = ""
        self.active: Console | None = None
        self.log = log

    @property
    def windowed(self) -> bool:
        """One tmux window per console (tabs, or `single` with several consoles)."""
        return self.layout not in SPLIT_PRESETS

    async def create(self, scenario: Scenario, width: int, height: int) -> None:
        await self.tmux.detect_version()
        # A server left on this socket (a guest rebuilt after `vm: reboot` without really
        # rebooting, or an earlier crash) would clash with the new session.
        await self.tmux.kill_server()
        await self.transport.make_dir(self.runtime_dir)
        self.layout = scenario.layout
        self.default_prompt = scenario.defaults.prompt
        self.specs = {c.name: c for c in scenario.consoles}
        conf = TMUX_CONF
        if not self.windowed:
            conf += PANES_CONF
        elif self.layout == "tabs":
            conf += TABS_CONF
        conf_path = f"{self.runtime_dir}/tmux.conf"
        await self.transport.write_file(conf_path, conf)

        first = scenario.consoles[0]
        command, status = await self._command(first)
        out = await self.tmux(
            "-f", conf_path, "new-session", "-d", "-P", "-F", "#{window_id} #{pane_id}",
            "-s", SESSION, "-n", first.title or first.name, "-x", str(width),
            "-y", str(height), "-c", self._local_cwd(first), command)
        await self._register(first, out, status)
        for spec in scenario.consoles[1:]:
            if spec.start:
                await self._open(spec)
        await self.arrange()
        await self.activate(self.consoles[first.name])

    def _local_cwd(self, spec: ConsoleSpec) -> str:
        # A remote console's cwd is on the other machine; locally it starts in ~.
        return self.transport.expand_user("~" if spec.host else spec.cwd)

    async def _command(self, spec: ConsoleSpec) -> tuple[str, str | None]:
        if spec.host:
            return remote_shell_command(spec), None  # no hidden hook on another machine
        return await self._shell_command(spec)

    async def _register(self, spec: ConsoleSpec, tmux_out: str, status: str | None) -> Console:
        window, pane = tmux_out.split()
        console = Console(spec, self.tmux, pane, spec.prompt or self.default_prompt, status)
        console.window = window
        await self.tmux("set-option", "-p", "-t", pane, "@sp_title", spec.title or spec.name)
        self.consoles[spec.name] = console
        return console

    async def _open(self, spec: ConsoleSpec) -> Console:
        command, status = await self._command(spec)
        title = spec.title or spec.name
        cwd = self._local_cwd(spec)
        if self.windowed:
            out = await self.tmux("new-window", "-d", "-P", "-F", "#{window_id} #{pane_id}",
                                  "-t", f"{SESSION}:", "-n", title, "-c", cwd, command)
        else:
            last = list(self.consoles.values())[-1]  # split after it: panes keep YAML order
            direction = "-h" if self.layout == "split-horizontal" else "-v"
            out = await self.tmux("split-window", "-d", direction, "-P", "-F",
                                  "#{window_id} #{pane_id}", "-t", last.pane, "-c", cwd,
                                  command)
        return await self._register(spec, out, status)

    # --- layout ------------------------------------------------------------------------

    async def arrange(self) -> None:
        """Apply the layout preset and pane sizes. Called again after the terminal window
        attaches (the window takes the terminal's size) and after opening or closing."""
        if self.windowed or not self.consoles:
            return
        window = next(iter(self.consoles.values())).window
        assert window is not None
        await self.tmux("select-layout", "-t", window, SPLIT_PRESETS[self.layout])
        if self.layout == "grid":
            return
        size = (await self.tmux("display-message", "-p", "-t", window,
                                "#{window_width} #{window_height}")).split()
        total = int(size[0] if self.layout == "split-horizontal" else size[1])
        flag = "-x" if self.layout == "split-horizontal" else "-y"
        for console in self.consoles.values():
            cells = _cells(console.spec.size, total)
            if cells:
                await self.tmux("resize-pane", "-t", console.pane, flag, str(cells))

    async def activate(self, console: Console) -> bool:
        """Make this console the visible, highlighted one. Returns True if it changed."""
        if console.closed:
            raise StepFailed(f"console {console.name!r} is closed")
        if self.active is console:
            return False
        if self.windowed:
            await self.tmux("select-window", "-t", console.window or "")
        await self.tmux("select-pane", "-t", console.pane)
        self.active = console
        return True

    async def zoom(self, console: Console, on: bool) -> None:
        """Make one pane fill the window (spec 9.2 `focus` with `zoom`), or undo it."""
        await self.activate(console)
        if self.windowed:
            return
        zoomed = (await self.tmux("display-message", "-p", "-t", console.pane,
                                  "#{window_zoomed_flag}")).strip() == "1"
        if zoomed != on:
            await self.tmux("resize-pane", "-Z", "-t", console.pane)

    # --- opening and closing mid-take ----------------------------------------------------

    async def open_console(self, name: str, timeout: float = 20.0) -> Console:
        if name in self.consoles:
            raise StepFailed(f"console {name!r} is already open")
        spec = self.specs[name]
        self.closed.pop(name, None)
        console = await self._open(spec)
        await self.arrange()
        await self._wait_first_prompt(console, timeout)
        return console

    async def close_console(self, name: str) -> None:
        console = self.consoles.get(name)
        if console is None:
            raise StepFailed(f"console {name!r} is not open")
        if len(self.consoles) == 1:
            raise StepFailed("cannot close the last open console")
        console.final_history = await console.history()
        await self.tmux("kill-pane", "-t", console.pane)
        console.closed = True
        del self.consoles[name]
        self.closed[name] = console
        if self.active is console:
            self.active = None
            await self.activate(next(iter(self.consoles.values())))
        await self.arrange()

    def all_consoles(self) -> dict[str, Console]:
        """Open and closed consoles, for transcripts."""
        return {**self.closed, **self.consoles}

    async def _shell_command(self, spec: ConsoleSpec) -> tuple[str, str | None]:
        base = f"{self.runtime_dir}/{spec.name}"
        status = f"{base}.status"
        env_lines = "\n".join(f"export {k}={shlex.quote(v)}" for k, v in spec.env.items())
        values = dict(HISTFILE=shlex.quote(f"{base}.history"), STATUS=shlex.quote(status),
                      ENV=env_lines)
        if spec.shell == "bash":
            rc = f"{base}.bashrc"
            await self.transport.write_file(rc, _render(_hook_template("bash_rc.sh"), **values))
            return f"exec bash --rcfile {shlex.quote(rc)} -i", status
        if spec.shell == "zsh":
            zdot = f"{base}.zsh"
            await self.transport.make_dir(zdot)
            await self.transport.write_file(f"{zdot}/.zshenv", _hook_template("zshenv.zsh"))
            await self.transport.write_file(
                f"{zdot}/.zshrc", _render(_hook_template("zshrc.zsh"), **values))
            return f"exec env ZDOTDIR={shlex.quote(zdot)} zsh -i", status
        exports = " ".join(f"{k}={shlex.quote(v)}" for k, v in spec.env.items())
        return f"exec env {exports} sh -i", None

    async def wait_attached(self, timeout: float = 15.0) -> None:
        """Wait until the terminal window has attached to the session."""
        loop = asyncio.get_running_loop()
        deadline = loop.time() + timeout
        while loop.time() < deadline:
            out = await self.tmux("list-clients", "-t", SESSION, "-F", "#{client_name}",
                                  check=False)
            if out.strip():
                await asyncio.sleep(0.8)  # let the window reach its final size and repaint
                size = await self.tmux("list-clients", "-t", SESSION, "-F",
                                       "#{client_width}x#{client_height}", check=False)
                self.log("info", f"terminal window: {size.strip()} cells (without a window "
                                 "manager, e.g. bare Xvfb, it cannot go full screen)")
                return
            await asyncio.sleep(0.2)
        raise EnvironmentProblem(
            f"the terminal window did not attach to tmux within {timeout:.0f}s")

    async def wait_ready(self, timeout: float = 20.0) -> None:
        """Wait for each console's first prompt; detect whether the shell hook works."""
        for console in self.consoles.values():
            await self._wait_first_prompt(console, timeout)

    async def _wait_first_prompt(self, console: Console, timeout: float) -> None:
        loop = asyncio.get_running_loop()
        deadline = loop.time() + timeout
        last = ""
        while loop.time() < deadline:
            info = await console.info()
            if info.dead:
                screen = "\n".join(await console.capture())
                raise EnvironmentProblem(
                    f"console {console.name!r}: the shell exited at start:\n{screen}")
            status = await console.status()
            lines = [ln for ln in await console.capture() if ln.strip()]
            last = lines[-1] if lines else ""
            hook_ready = status is not None or console.status_path is None
            if hook_ready and last and console.prompt_matches(last):
                console.hook_ok = status is not None
                if console.status_path and not console.hook_ok:
                    self.log("warning", f"console {console.name!r}: shell hook inactive; "
                                        "prompt detection uses the regex only")
                return
            if (status is None and console.status_path and last
                    and console.prompt_matches(last) and loop.time() > deadline - timeout / 2):
                # The prompt is there but the hook never reported: carry on without it.
                console.status_path = None
                continue
            await asyncio.sleep(0.2)
        raise EnvironmentProblem(
            f"console {console.name!r}: the prompt regex {console.prompt_re.pattern!r} does "
            f"not match the shell prompt. Last line on screen: {last!r}. Set `prompt` in "
            "`defaults` or on the console.")

    async def clear(self) -> None:
        """Clear every console that sits at a prompt, including its scrollback."""
        for console in self.consoles.values():
            info = await console.info()
            if info.alternate_on:
                continue
            line = await console.current_line_before_cursor(info)
            if not console.prompt_matches(line):
                continue
            await console.send_key("C-l")
            await asyncio.sleep(0.3)
            await self.tmux("clear-history", "-t", console.pane)
            console.output_start = None
            console.input_start = None

    async def close(self) -> None:
        await self.tmux.kill_server()
