"""The take's tmux session: private server, generated config, consoles with shell hooks."""

from __future__ import annotations

import asyncio
import shlex
from collections.abc import Callable
from importlib.resources import files

from ..errors import EnvironmentProblem
from ..loader.model import ConsoleSpec, Scenario
from ..transport import Transport
from .driver import Console
from .tmux import Tmux

SESSION = "scenarioplay"

TMUX_CONF = """\
# Generated by ScenarioPlay for one take.
set -g history-limit 100000
set -g escape-time 0
set -g status off
set -g mouse off
set -g set-titles off
set -g bell-action none
set -g visual-bell off
set -g default-terminal "screen-256color"
setw -g remain-on-exit on
setw -g allow-rename off
setw -g automatic-rename off
"""


def _hook_template(name: str) -> str:
    return (files("scenarioplay.console") / "hooks" / name).read_text(encoding="utf-8")


def _render(template: str, **values: str) -> str:
    for key, value in values.items():
        template = template.replace(f"@@{key}@@", value)
    return template


class Session:
    def __init__(self, transport: Transport, runtime_dir: str, take_id: str,
                 log: Callable[[str, str], None]):
        self.transport = transport
        self.runtime_dir = runtime_dir
        self.tmux = Tmux(transport, f"scenarioplay-{take_id}")
        self.consoles: dict[str, Console] = {}
        self.log = log

    async def create(self, scenario: Scenario, width: int, height: int) -> None:
        await self.tmux.detect_version()
        await self.transport.make_dir(self.runtime_dir)
        conf = f"{self.runtime_dir}/tmux.conf"
        await self.transport.write_file(conf, TMUX_CONF)

        default_prompt = scenario.defaults.prompt
        for index, spec in enumerate(scenario.consoles):
            command, status = await self._shell_command(spec)
            cwd = self.transport.expand_user(spec.cwd)
            title = spec.title or spec.name
            if index == 0:
                pane = await self.tmux(
                    "-f", conf, "new-session", "-d", "-P", "-F", "#{pane_id}",
                    "-s", SESSION, "-n", title, "-x", str(width), "-y", str(height),
                    "-c", cwd, command)
            else:  # phase 3 adds layouts; extra consoles become windows for now
                pane = await self.tmux(
                    "new-window", "-d", "-P", "-F", "#{pane_id}", "-t", SESSION,
                    "-n", title, "-c", cwd, command)
            self.consoles[spec.name] = Console(
                spec, self.tmux, pane.strip(), spec.prompt or default_prompt, status)

    async def _shell_command(self, spec: ConsoleSpec) -> tuple[str, str | None]:
        base = f"{self.runtime_dir}/{spec.name}"
        status = f"{base}.status"
        env_lines = "\n".join(f"export {k}={shlex.quote(v)}" for k, v in spec.env.items())
        values = dict(HISTFILE=shlex.quote(f"{base}.history"), STATUS=shlex.quote(status),
                      ENV=env_lines)
        if spec.shell == "bash":
            rc = f"{base}.bashrc"
            await self.transport.write_file(rc, _render(_hook_template("bash_rc.sh"), **values))
            return f"exec bash --rcfile {shlex.quote(rc)} -i", status
        if spec.shell == "zsh":
            zdot = f"{base}.zsh"
            await self.transport.make_dir(zdot)
            await self.transport.write_file(f"{zdot}/.zshenv", _hook_template("zshenv.zsh"))
            await self.transport.write_file(
                f"{zdot}/.zshrc", _render(_hook_template("zshrc.zsh"), **values))
            return f"exec env ZDOTDIR={shlex.quote(zdot)} zsh -i", status
        exports = " ".join(f"{k}={shlex.quote(v)}" for k, v in spec.env.items())
        return f"exec env {exports} sh -i", None

    async def wait_attached(self, timeout: float = 15.0) -> None:
        """Wait until the terminal window has attached to the session."""
        loop = asyncio.get_running_loop()
        deadline = loop.time() + timeout
        while loop.time() < deadline:
            out = await self.tmux("list-clients", "-t", SESSION, "-F", "#{client_name}",
                                  check=False)
            if out.strip():
                await asyncio.sleep(0.8)  # let the window reach its final size and repaint
                size = await self.tmux("list-clients", "-t", SESSION, "-F",
                                       "#{client_width}x#{client_height}", check=False)
                self.log("info", f"terminal window: {size.strip()} cells (without a window "
                                 "manager, e.g. bare Xvfb, it cannot go full screen)")
                return
            await asyncio.sleep(0.2)
        raise EnvironmentProblem(
            f"the terminal window did not attach to tmux within {timeout:.0f}s")

    async def wait_ready(self, timeout: float = 20.0) -> None:
        """Wait for each console's first prompt; detect whether the shell hook works."""
        for console in self.consoles.values():
            await self._wait_first_prompt(console, timeout)

    async def _wait_first_prompt(self, console: Console, timeout: float) -> None:
        loop = asyncio.get_running_loop()
        deadline = loop.time() + timeout
        last = ""
        while loop.time() < deadline:
            info = await console.info()
            if info.dead:
                screen = "\n".join(await console.capture())
                raise EnvironmentProblem(
                    f"console {console.name!r}: the shell exited at start:\n{screen}")
            status = await console.status()
            lines = [ln for ln in await console.capture() if ln.strip()]
            last = lines[-1] if lines else ""
            hook_ready = status is not None or console.status_path is None
            if hook_ready and last and console.prompt_matches(last):
                console.hook_ok = status is not None
                if console.status_path and not console.hook_ok:
                    self.log("warning", f"console {console.name!r}: shell hook inactive; "
                                        "prompt detection uses the regex only")
                return
            if (status is None and console.status_path and last
                    and console.prompt_matches(last) and loop.time() > deadline - timeout / 2):
                # The prompt is there but the hook never reported: carry on without it.
                console.status_path = None
                continue
            await asyncio.sleep(0.2)
        raise EnvironmentProblem(
            f"console {console.name!r}: the prompt regex {console.prompt_re.pattern!r} does "
            f"not match the shell prompt. Last line on screen: {last!r}. Set `prompt` in "
            "`defaults` or on the console.")

    async def clear(self) -> None:
        """Clear every console that sits at a prompt, including its scrollback."""
        for console in self.consoles.values():
            info = await console.info()
            if info.alternate_on:
                continue
            line = await console.current_line_before_cursor(info)
            if not console.prompt_matches(line):
                continue
            await console.send_key("C-l")
            await asyncio.sleep(0.3)
            await self.tmux("clear-history", "-t", console.pane)
            console.output_start = None
            console.input_start = None

    async def close(self) -> None:
        await self.tmux.kill_server()
